### ISSUE TITLE
Renamed movie not taken in mind

### ISSUE THREAD

**Issue by Rubueno** [joshualyon/radarr-sub-downloader#1]
My set up renames a movie's filename from `BlacKkKlansman.2018.MULTi.2160p.UHD.BluRay.x265-SESKAPiLE.mkv` to `BlacKkKlansman (2018) [Bluray-2160p].mkv`. The subs downloader does not take this in mind and saves the subs as `BlacKkKlansman.2018.MULTi.2160p.UHD.BluRay.x265-SESKAPiLE.en.srt`. sonarr-sub-downloader does handle renaming of files. Can this be implemented in radarr-sub-downloader?

**Comment by joshualyon** [comment]
Depending on where the renaming is taking place, it probably could... but I'm not actively developing this, so you would need to fork it and make the modifications yourself. 😃 

From a quick look, it looks like there is a rename event from Radarr. The challenge might be in timing as the sub downloader script might still be running when the rename event comes in, so you would have to handle that potential concurrency/race condition:
https://github.com/Radarr/Radarr/wiki/Custom-Post-Processing-Scripts
